In [1]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
c=np.tensordot(a,b,axes=0)
print(c)

[[ 4  5  6  7]
 [ 8 10 12 14]
 [12 15 18 21]
 [16 20 24 28]]


In [1]:
import numpy as np
a=np.array([[1,2,3]])
b=np.array([3,4,5])
# c=np.append(a,b,axis=0)
# c=np.concatenate((a,b),axis=0)
# c=np.concatenate(c)
print(a,b.transpose().shape)

[[1 2 3]] (3,)


In [2]:
import numpy as np
a=range(0,300,10)
b=range(0,90,3)
c=zip(a,b)
print([(x,y) for x,y in c])

[(0, 0), (10, 3), (20, 6), (30, 9), (40, 12), (50, 15), (60, 18), (70, 21), (80, 24), (90, 27), (100, 30), (110, 33), (120, 36), (130, 39), (140, 42), (150, 45), (160, 48), (170, 51), (180, 54), (190, 57), (200, 60), (210, 63), (220, 66), (230, 69), (240, 72), (250, 75), (260, 78), (270, 81), (280, 84), (290, 87)]


In [73]:
import numpy as np
import scipy.signal as sp
import matplotlib.pylab as plt

def form(ipt,knl,stp=(1,1)):
    rst=[]
    for i in range(0,ipt[0]-knl[0]+1,stp[0]):
        for j in range(0,ipt[1]-knl[1]+1,stp[1]):
            rst.append([(m+i)*ipt[1]+n+j for m in range(knl[0]) for n in range(knl[1])])
    return np.array(rst)

img=plt.imread('tst.jpg')
dat=img[:,:,0]
knl=np.array([[1,1,1],[1,1,0],[1,0,0]])
fm=form(dat.shape,knl.shape)
%timeit rst1=sp.correlate2d(dat,knl,mode='valid')
%timeit rst=np.dot(dat.flatten()[fm],knl.flatten())
%time tp=np.any(rst.reshape((405,598))-rst1)
print(tp)

36.1 ms ± 534 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
49.4 ms ± 869 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
Wall time: 0 ns
False


In [81]:
import numpy as np
import scipy.ndimage as sp
import matplotlib.pylab as plt

img=plt.imread('tst.jpg')
dat=img[:,:,0]
knl=np.array([[1,0,0],[0,1,0],[0,0,1]])

%timeit rst=sp.correlate(dat,knl)


7.18 ms ± 105 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
