In [1]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
c=np.tensordot(a,b,axes=0)
print(c)

[[ 4  5  6  7]
 [ 8 10 12 14]
 [12 15 18 21]
 [16 20 24 28]]


In [1]:
import numpy as np
a=np.array([[1,2,3]])
b=np.array([3,4,5])
# c=np.append(a,b,axis=0)
# c=np.concatenate((a,b),axis=0)
# c=np.concatenate(c)
print(a,b.transpose().shape)

[[1 2 3]] (3,)


In [19]:
import numpy as np
a=range(0,300,10)
b=range(0,90,3)
c=zip(a,b)
print([(x,y) for x,y in c])
print(dir(c))

[(0, 0), (10, 3), (20, 6), (30, 9), (40, 12), (50, 15), (60, 18), (70, 21), (80, 24), (90, 27), (100, 30), (110, 33), (120, 36), (130, 39), (140, 42), (150, 45), (160, 48), (170, 51), (180, 54), (190, 57), (200, 60), (210, 63), (220, 66), (230, 69), (240, 72), (250, 75), (260, 78), (270, 81), (280, 84), (290, 87)]
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__lt__', '__ne__', '__new__', '__next__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
